const NOT_FOUND = 404;
const VALIDATION_ERROR = 400;
const CONFLICT_ERROR = 409;
const FORBIDDEN = 403;
const UNAUTHORIZED = 401;

module.exports = {
  NOT_FOUND,
  VALIDATION_ERROR,
  CONFLICT_ERROR,
  FORBIDDEN,
  UNAUTHORIZED,
};
